### ISSUE TITLE
Compare this lib to https://github.com/stonewell/freetype-direct-gl

### ISSUE THREAD

**Issue by KOLANICH** [fetisov/ttf2mesh#1]

**Comment by fetisov** [comment]
Hello. Thanks for the link. The results of this work are quite interesting. The main difference from ttf2mesh is that freetype-direct-gl uses a bitmap technique to render the glyph. Triangulation is not used explicitly. The advantage of freetype-direct-gl over ttf2mesh is that freetype-direct-gl does not require computation on the CPU. The disadvantage of freetype-direct-gl is that freetype-direct-gl will not allow rendering of 3d text, since the finished mesh object is not stored in memory. There are also questions about the side effects of suboptimal mesh output by the freetype-direct-gl library. The ttf2mesh library takes care of optimizing the mesh object before displaying it.
